line-length = 100
exclude = [
  ".tox",
  ".eggs",
  "build",
]

[lint]
select = [
  "C4",  # flake8-comprehensions
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F",  # Pyflakes
]
extend-select = [
  "COM",  # flake8-commas
]
ignore = [
  # py  # pycodestyle (E, W)
  "E501",  # line-too-long
  "E711",  # NoneComparison  (see unfixable)
  "E721",  # type-comparison
  "E731",  # lambda-assignment
  "E741",  # AmbiguousVariableName. Physics variables are often poor code variables

  # Pyflakes (F)
  "F841",  # unused-variable

  # flake8-commas (COM)
  "COM812",  # TrailingCommaMissing
  "COM819",  # TrailingCommaProhibited
]
unfixable = [
  "E711"  # NoneComparison. Hard to fix b/c numpy has it's own None.
]

[lint.extend-per-file-ignores]
"setup.py" = [
  "INP001",  # Part of configuration, not a package.
  "ICN001",
  "UP018"
]
"test_*.py" = [
  "ANN201",  # Public function without return type annotation
  "B018",  # UselessExpression
  "D",  # pydocstyle
  "S101",  # Use of assert detected
]
"conftest.py" = ["INP001"]  # Part of configuration, not a package.
"docs/*.py" = [
  "INP001",  # implicit-namespace-package. The examples are not a package.
  "PLC0415",  # import-outside-top-level
]

[lint.flake8-annotations]
ignore-fully-untyped = true
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-type-checking]
exempt-modules = []

[lint.isort]
known-first-party = ["astropy", "extension_helpers"]

[lint.pydocstyle]
convention = "numpy"
